# Generated by Django 3.1.1 on 2021-03-08 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0004_auto_20210307_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 8, 10, 37, 34, 362417)),
        ),
    ]
