# Generated by Django 3.1.1 on 2021-03-09 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0005_auto_20210308_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_grade',
            field=models.CharField(default='5/6', max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 9, 19, 22, 57, 676015)),
        ),
    ]
